server:
  port: 8087

spring:
  application:
    name: javayh-elastic
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data
      local: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false
#    username: root
#    password: 1219320
#    driver-class-name: com.mysql.jdbc.Driver
#
#mybatis:
#  dao-locations: classpath:dao/*.mapper
#  type-aliases-package: com.javayh.entity

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
