server:
  port: 8021

dubbo:
  application:
    name: javayh-dubbo-server
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  #通信规则（通信协议和接口）
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry
#开启包扫描，可替代 @EnableDubbo 注解
#  scan:
#    base-packages: com.javayh