server:
  port: 8016
spring:
  profiles:
    active: dev
  application:
    name: javayh-elasticjob
##数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elastic_job?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 1219320
    druid:
      initial-size: 3
      max-active: 10
      min-idle: 5
      max-wait: 600000
      validation-query: SELECT 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 600000
      filters: stat,wall

info:
  app_name: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
##zookeeper配置
javayh:
  elasticjob:
    zk-config:
      serverLists: localhost:2181
      namespace: elastic-job-lite-demo
      baseSleepTimeMilliseconds: 1000
      maxSleepTimeMilliseconds: 3000
      maxRetries: 4
      digest: 'password'

mybatis:
  type-aliases-package: com.javayh.entity
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map空列不显示问题
  mapper-locations:
  - classpath:mybatis/*.mapper

logging:
  level:
    com.javayh.mapper: DEBUG